name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write
  actions: write
  id-token: write

jobs:
  release:
    name: Semantic Versioning Auto Tag and Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Setup Git
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/ylongwang2782/wht_slave.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Git History
        shell: bash
        run: |
          echo "Recent commits:"
          git log --oneline -10
          echo "Current branch:"
          git branch -a

      - name: Create Release
        shell: bash
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: package_version
        run: |
            VERSION=$(git describe --tags --abbrev=0)
            VERSION=${VERSION#v} # 移除前缀 v
            echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.29.2"

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
        with:
          version: "1.12.1"

      - name: Setup ARM GCC
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "14.2.Rel1"

      - name: Build Firmware
        shell: bash
        run: |
          cmake --preset debug
          cmake --build build

          VERSION=$(git describe --tags --abbrev=0)
          VERSION=${VERSION#v} # 移除前缀 v

          cp build/debug/wht_slave.hex wht_slave_v${VERSION}.hex

          echo "FIRMWARE_NAME=wht_slave_v${VERSION}.hex" >> $GITHUB_ENV

      - name: Clean Build Directory
        shell: bash
        run: rm -rf build/*

      - name: Upload Release Assets
        shell: bash
        run: |
          # 获取最新的 release tag
          LATEST_TAG=$(git describe --tags --abbrev=0)

          # 上传重命名的固件文件
          gh release upload "$LATEST_TAG" "$FIRMWARE_NAME" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
